### ISSUE TITLE
Add git revert to context menu

### ISSUE THREAD

**Issue by ProLoser** [tualo/tualo-git-context#12]
So I can revert the changes to a file.

**Comment by thomashoffmann1979** [comment]
Thanks for your suggestion, i have added revert to HEAD in version v0.6.0.

**Comment by ProLoser** [comment]
You need to reopen this issue as this was implemented wrong and almost made me blow away a bunch of work. I wanted to revert ONE file, not the entire project.

**Comment by thomashoffmann1979** [comment]
Oh, it isn't git-revert reverts all changes on the given commit. At the moment this package only supports the last commit. Your changes aren't blown away since they were commited. git-revert records also the revert changes ( see http://git-scm.com/docs/git-revert ). But i think you mean git checkout filename? I will add it in the next version.

**Comment by ProLoser** [comment]
Sorry, I was implying traditional `revert` behavior, I wasn't thinking about literal `git revert` since I always use the `revert` shortcut in git gui. There should be no project-wide git commands I feel like in the context menu since context menu implies context.

**Comment by ProLoser** [comment]
I suppose what I meant was a `git reset` or `git checkout` as you say.
